#!/bin/bash
DIR="/opt/ambient-light-sensor"
STATUS=$(als-controller -s)
if [ "$STATUS" = "0" ]; then
  als-controller -e
  notify-send -c "device" -i "$DIR/"'active.svg' 'Ambient Light Sensor' 'Enabled'
elif [ "$STATUS" = "1" ]; then
  als-controller -d
  notify-send -c "device" -i "$DIR/"'inactive.svg' 'Ambient Light Sensor' 'Disabled'
else
  echo "Error: $STATUS"
fi
